[theme]
primaryColor = "#FFB3D9"
backgroundColor = "#FAFAFA" 
secondaryBackgroundColor = "#E6D7FF"
textColor = "#8B4C8C"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
